project_id = "eyvfrocuuhxleroghybv"

[functions.send-newsletter]
verify_jwt = true

[functions.send-appointment-reminders]
verify_jwt = false

[functions.translate-property]
verify_jwt = true

[functions.migrate-project-images]
verify_jwt = true

[functions.manage-users]
verify_jwt = true

[functions.property-chatbot]
verify_jwt = false

[functions.convert-image-webp]
verify_jwt = true

[functions.scheduled-image-conversion]
verify_jwt = false

[functions.send-conversion-notification]
verify_jwt = true
